/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 23558a27cec775cec26a9a2bbbd98290)
interface __BaseEnv_Env {
  DB: D1Database;
  AI: Ai;
  DATABASE_PROVIDER: "d1";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_PROVIDER">> {}
}
